{% set name = "pydeps" %}
{% set version = "1.10.16" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pydeps-{{ version }}.tar.gz
  sha256: da5d1bd4bc2a8ac4d63f46ca1bcf701869a5c2549b64c3fad060de03b8925982

build:
  noarch: python
  number: 0
  entry_points:
    - pydeps = pydeps.pydeps:pydeps
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - stdlib-list

test:
  imports:
    - pydeps
  commands:
    - pip check
    - pydeps --help
  requires:
    - pip

about:
  home: https://github.com/thebjorn/pydeps
  summary: Display module dependencies
  doc_url: https://pythonhosted.org/pydeps/
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
