{% set name = "pydeps" %}
{% set version = "3.0.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pydeps-{{ version }}.tar.gz
  sha256: 9e73575ddd6b5614cb2463a4ee9392817cc51002a2e46184d4fb1ffef8d15832

build:
  noarch: python
  number: 0
  entry_points:
    - pydeps = pydeps.pydeps:pydeps
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - stdlib-list

test:
  imports:
    - pydeps
  commands:
    - pip check
    - pydeps --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/thebjorn/pydeps
  summary: Display module dependencies
  doc_url: https://pythonhosted.org/pydeps/
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
